## /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  ##
# This is where you put your own keybinds. Be Mindful to check as well ~/.config/hypr/configs/Keybinds.conf to avoid conflict
# if you think I should replace the Pre-defined Keybinds in ~/.config/hypr/configs/Keybinds.conf , submit an issue or let me know in DC and present me a valid reason as to why, such as conflicting with global shortcuts, etc etc

# See https://wiki.hyprland.org/Configuring/Keywords/ for more settings and variables
# See also Laptops.conf for laptops keybinds 

$mainMod = SUPER
$files = thunar
$term = kitty
$scriptsDir = $HOME/.config/hypr/scripts
$UserScripts = $HOME/.config/hypr/UserScripts

# rofi App launcher
#bindr = $mainMod, $mainMod_L, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window
bind = $mainMod, D, exec, pkill rofi || rofi -show drun -modi drun,filebrowser,run,window

bind = $mainMod, Return, exec, $term  # Launch terminal
bind = $mainMod, T, exec, $files

# User Added Keybinds
bind = $mainMod SHIFT, O, exec, $UserScripts/ZshChangeTheme.sh # Change oh-my-zsh theme
bind = $mainMod CTRL, l, swapwindow, l
bind = $mainMod CTRL, r, swapwindow, r
bind = $mainMod CTRL, u, swapwindow, u
bind = $mainMod CTRL, d, swapwindow, d
#bind = $mainMod CTRL SHIFT, 1, movewindow, mon:+1
#bind = $mainMod CTRL SHIFT, 2, movewindow, mon:-1

# User bind for emote
bind = $mainMod SHIFT, period, exec, flatpak run com.tomjwatson.Emote

#User bind for hide window
bind = $mainMod, H, movetoworkspacesilent, special:minimized
bind = $mainMod, W, movetoworkspacesilent, +0
bind = $mainMod, W, togglespecialworkspace, minimized

#Change Default Keybinding
bind = $mainMod SHIFT, Q, exec, hyprctl kill
bind = $mainMod SHIFT, H, exec, $scriptsDir/KeyHints.sh
bind = $mainMod SHIFT, W, exec, $UserScripts/WallpaperSelect.sh

#Bind for drag window
bindm=ALT,mouse:272,movewindow
bindm=ALT,mouse:273,resizewindow

# For passthrough keyboard into a VM
# bind = $mainMod ALT, P, submap, passthru
#submap = passthru
# to unbind
#bind = $mainMod ALT, P, submap, reset
#submap = reset
